import avatar from '../assets/logo192.png'
import avatar1 from '../assets/avt1.jpg'
import avatar2 from '../assets/avt2.jpg'

const user = [{
    id: "1",
    name: "Nguyen Minh Hung1",
    email: "hung.nguyen@gmail.com",
    permission: "RECer",
    date: "Sep 9, 2020",
    avt: avatar1,
    username: "minhhung123",
},
{
    id: "2",
    name: "Nguyen Minh Hung2",
    email: "hung.nguyen@gmail.com",
    permission: "RECer",
    date: "Sep 9, 2020",
    avt: avatar,
    username: "minhhung123",
},
{
    id: "3",
    name: "Nguyen Minh Hung3",
    email: "hung.nguyen@gmail.com",
    permission: "RECer",
    date: "Sep 9, 2020",
    avt: avatar2,
    username: "minhhung123",
},
{
    id: "4",
    name: "Nguyen Minh Hung4",
    email: "hung.nguyen@gmail.com",
    permission: "Interviewer",
    date: "Sep 9, 2020",
    avt: avatar,
    username: "minhhung123",
},
{
    id: "5",
    name: "Nguyen Minh Hung5",
    email: "hung.nguyen@gmail.com",
    permission: "Interviewer",
    date: "Sep 9, 2020",
    avt: avatar2,
    username: "minhhung123",
},
{
    id: "6",
    name: "Nguyen Minh An",
    email: "hung.nguyen@gmail.com",
    permission: "Interviewer",
    date: "Sep 9, 2020",
    avt: avatar1,
    username: "minhhung123",
},
{
    id: "7",
    name: "Nguyen Minh Hung6",
    email: "hung.nguyen@gmail.com",
    permission: "Interviewer",
    date: "Sep 9, 2020",
    avt: avatar,
    username: "minhhung123",
},
{
    id: "8",
    name: "Nguyen Minh Hung7",
    email: "hung.nguyen@gmail.com",
    permission: "Interviewer",
    date: "Sep 9, 2020",
    avt: avatar2,
    username: "minhhung123",
},
{
    id: "9",
    name: "Nguyen Minh Hung8",
    email: "hung.nguyen@gmail.com",
    permission: "Interviewer",
    date: "Sep 9, 2020",
    avt: avatar1,
    username: "minhhung123",
},
{
    id: "10",
    name: "Nguyen Minh Hung9",
    email: "hung.nguyen@gmail.com",
    permission: "Candidate",
    date: "Sep 9, 2020",
    avt: avatar2,
    position: "FE: React",
    status: "Accept",
    username: "minhhung123",
    score: 9,
    skills: "JavaScript, React",
    experience: "3",
},
{
    id: "11",
    name: "Nguyen Minh Hung10",
    email: "hung.nguyen@gmail.com",
    permission: "Candidate",
    date: "Sep 9, 2020",
    avt: avatar1,
    position: "FE: React",
    status: "In process",
    username: "minhhung123",
    score: 7,
    skills: "JavaScript, React",
    experience: "3",
},
{
    id: "12",
    name: "Nguyen Minh Hung11",
    email: "hung.nguyen@gmail.com",
    permission: "Candidate",
    date: "Sep 9, 2020",
    avt: avatar1,
    position: "FE: Vuejs",
    status: "In process",
    username: "minhhung123",
    score: 7,
    skills: "JavaScript, Vue",
    experience: "3",
},
{
    id: "13",
    name: "Nguyen Minh Hung12",
    email: "hung.nguyen@gmail.com",
    permission: "Candidate",
    date: "Sep 9, 2020",
    avt: avatar2,
    position: "BE: Java",
    status: "Blacklist",
    username: "minhhung123",
    score: 0,
    skills: "Java",
    experience: "3",
},
{
    id: "14",
    name: "Nguyen Minh Hung13",
    email: "hung.nguyen@gmail.com",
    permission: "Candidate",
    date: "Sep 9, 2020",
    avt: avatar2,
    position: "FE: React",
    status: "Accept",
    username: "minhhung123",
    score: 8,
    skills: "JavaScript, React",
    experience: "3",
},
{
    id: "15",
    name: "Nguyen Minh Hung14",
    email: "hung.nguyen@gmail.com",
    permission: "Candidate",
    date: "Sep 9, 2020",
    avt: avatar1,
    position: "FE: React",
    status: "In process",
    username: "minhhung123",
    score: 7,
    skills: "JavaScript, React",
    experience: "2",
},
{
    id: "16",
    name: "Nguyen Minh Hung15",
    email: "hung.nguyen@gmail.com",
    permission: "Candidate",
    date: "Sep 9, 2020",
    avt: avatar2,
    position: "FE: React",
    status: "Accept",
    username: "minhhung123",
    score: 7.5,
    skills: "JavaScript, React",
    experience: "5",
},
{
    id: "17",
    name: "Nguyen Minh Hung16",
    email: "hung.nguyen@gmail.com",
    permission: "Candidate",
    date: "Sep 9, 2020",
    avt: avatar1,
    position: "FE: React",
    status: "In process",
    username: "minhhung123",
    score: 7,
    skills: "JavaScript, React",
    experience: "3",
},
{
    id: "18",
    name: "Nguyen Minh Hung17",
    email: "hung.nguyen@gmail.com",
    permission: "Candidate",
    date: "Sep 9, 2020",
    avt: avatar1,
    position: "FE: Vuejs",
    status: "In process",
    username: "minhhung123",
    score: 7,
    skills: "JavaScript, Vue",
    experience: "1",
},
{
    id: "19",
    name: "Nguyen Minh Anh",
    email: "hung.nguyen@gmail.com",
    permission: "Candidate",
    date: "Sep 9, 2020",
    avt: avatar2,
    position: "BE: Java",
    status: "Blacklist",
    username: "minhhung123",
    score: 0,
    skills: "Java",
    experience: "3",
},
{
    id: "20",
    name: "Nguyen Minh Hung18",
    email: "hung.nguyen@gmail.com",
    permission: "Candidate",
    date: "Sep 9, 2020",
    avt: avatar2,
    position: "FE: React",
    status: "Accept",
    username: "minhhung123",
    score: 9,
    skills: "JavaScript, React",
    experience: "3",
},
{
    id: "21",
    name: "Nguyen Minh Hung19",
    email: "hung.nguyen@gmail.com",
    permission: "Candidate",
    date: "Sep 9, 2020",
    avt: avatar2,
    position: "FE: React",
    status: "Accept",
    username: "minhhung123",
    score: 10,
    skills: "JavaScript, React",
    experience: "2",
},
{
    id: "22",
    name: "Nguyen Minh Hung20",
    email: "hung.nguyen@gmail.com",
    permission: "Candidate",
    date: "Sep 9, 2020",
    avt: avatar2,
    position: "FE: React",
    status: "Accept",
    username: "minhhung123",
    score: 8,
    skills: "JavaScript, React",
    experience: "3",
},
{
    id: "23",
    name: "Nguyen Minh Thanh",
    email: "hung.nguyen@gmail.com",
    permission: "Candidate",
    date: "Sep 9, 2020",
    avt: avatar2,
    position: "FE: React",
    status: "Accept",
    username: "minhhung123",
    score: 9,
    skills: "JavaScript, React",
    experience: "3",
},
{
    id: "24",
    name: "Nguyen Minh Khanh1",
    email: "hung.nguyen@gmail.com",
    permission: "Candidate",
    date: "Sep 9, 2020",
    avt: avatar2,
    position: "FE: React",
    status: "Accept",
    username: "minhhung123",
    score: 9,
    skills: "JavaScript, React",
    experience: "4",
},
{
    id: "25",
    name: "Nguyen Minh Khanh2",
    email: "hung.nguyen@gmail.com",
    permission: "Candidate",
    date: "Sep 9, 2020",
    avt: avatar2,
    position: "FE: React",
    status: "Accept",
    username: "minhhung123",
    score: 9,
    skills: "JavaScript, React",
    experience: "3",
},
];

export default user;